FROM scratch
MAINTAINER Michael Klimenko, mklimenko@golantelecom.co.il
ADD /home/golan/proj/bin/cgr-engine /usr/bin/cgr-engine
ENTRYPOINT ["/usr/bin/cgr-engine"]
CMD ["--logger=*stdout","--log_level=7"]	