FROM scratch
MAINTAINER Michael Klimenko, mklimenko@golantelecom.co.il
ADD /home/golan/proj/bin/cgr-tester /usr/bin/cgr-tester
ENTRYPOINT ["/usr/bin/cgr-tester"]
#CMD ["--logger=*stdout","--log_level=7"]	